name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build web-app
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
